#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC=sysctl
NAME=sysctl
COMMAND=/sbin/$NAME
CONFIG=/etc/sysctl.conf

# Gracefully exit if the package has been removed.
test -x $COMMAND || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
        $COMMAND -q -p $CONFIG
	echo "."
	;;
  stop) echo -n "Stopping $DESC: $NAME"
	echo "."
	;;
  restart) echo "Restarting $DESC: $NAME"
	$0 stop
	sleep 1
	$0 start
	;;
  *) echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
