#!/bin/sh

case "$1" in
	start)
		echo -n "Starting iptables: "
		sh /iptables.start
		sh /ip6tables.start
		[ $? == 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		echo -n "Stopping iptables: "
		sh /iptables.stop
		sh /ip6tables.stop
		[ $? == 0 ] && echo "OK" || echo "FAIL"
		;;
	restart)
		$0 stop
		sleep 2
		$0 start
		if [ "$?" != "0" ]; then
			exit 1
		fi
		;;
	*)
		echo "Usage: /etc/init.d/iptables {start|stop|restart}"
		exit 1
esac

exit 0
