#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON_SBIN=/usr/sbin/hostapd
DAEMON_CONF=/etc/hostapd.conf
PIDFILE=/var/run/hostapd.pid

[ -x "$DAEMON_SBIN" ] || exit 0
[ -n "$DAEMON_CONF" ] || exit 0

DAEMON_OPTS="-B -P $PIDFILE $DAEMON_OPTS $DAEMON_CONF"

case "$1" in
    start)
        echo -n "Starting hostapd: "
        start-stop-daemon -S -q -x "$DAEMON_SBIN" -p "$PIDFILE" -- $DAEMON_OPTS
        [ $? == 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        start-stop-daemon -K -q -x "$DAEMON_SBIN" -p "$PIDFILE"
        [ $? == 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart | force-reload)
        $0 stop
        sleep 2
        $0 start
        if [ "$?" != "0" ]; then
			exit 1
		fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

exit 0
